### PR TITLE
[_]: feat/workspaces-product-integration

### PR DESCRIPTION
**Pull request by apsantiso**
This PR prepares the payments service for handling business-related products events coming from Stripe.

### CODE REVIEW

**Comment by inxtci** [comment]
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Error from server (NotFound): applications.argoproj.io "preview-73-payments-server" not found**

**Comment by apsantiso** [comment]
/update-preview drive-server-wip-dev preview-287-bf270ebe0e6ec03a12247338b58414e999cdc0e4

**Pull request merged**
