### PR TITLE
[MKT-413]: fix/coupon codes

### PR DESCRIPTION
**Pull request by masterprog-cmd**
Check if the coupon can be used for each case:
- If it is for first purchase only.
- If it is for a specific plan.

Also a try catch has been added to the function that handles the customer.subscription.updated event so that it doesn't always pop a 500.

### CODE REVIEW

**Comment by inxtci** [comment]
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Progressing**

**Comment by inxtci** [comment]
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Degraded**

**Comment by inxtci** [comment]
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Degraded**

**Comment by inxtci** [comment]
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Degraded**

**Review by sg-gs — APPROVED** [review]

**Pull request merged**
