### PR TITLE
Feat/b2b main debug

### PR DESCRIPTION
**Pull request by apsantiso**

### CODE REVIEW

**Comment by apsantiso** [comment]
/update-preview drive-server-wip preview-287-f2b11b096112f3a38ccce5f0e067fd3ae4ccfb66 imageSuffix=-dev

**Comment by apsantiso** [comment]
/update-preview drive-server-wip preview-287-f2b11b096112f3a38ccce5f0e067fd3ae4ccfb66 imageSuffix=-dev

**Comment by apsantiso** [comment]
/update-preview drive-server-wip preview-287-f2b11b096112f3a38ccce5f0e067fd3ae4ccfb66 imageSuffix=-dev

**Comment by apsantiso** [comment]
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

**Comment by apsantiso** [comment]
/update-preview drive-server-wip preview-287-869db915d42398580aa4b2415c85ebcdafe2019f imageSuffix=-dev

**Comment by inxtci** [comment]
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Degraded**

**Pull request closed without merging**
